"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar/NavBar";
import { Footer } from "../components/Footer/Footer";
import { AuthProvider } from "@/Context/AuthContext";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [token, setToken] = useState<string>("");

  return (
    <html lang="en">
      {/* min-h-screen flex flex-col, lo que hace indicar el minimo de altura del body sea la pantalla */}
      <AuthProvider>
      {/* <body className={inter.className}> */}

        <body className={`${inter.className} bg-gray-800 text-white min-h-screen flex flex-col`}>
          <NavBar token={token} setToken={setToken} />
          {/* Esto hace que si el children es más chico el footer, por ejemplo, se pueda ajustar a la pantalla */}
          <main className="flex-grow">{children}</main>
          <Footer />
        </body>
      </AuthProvider>
    </html>
  );
}
